### ISSUE TITLE
regra do ficaem(LOCAL1, LOCAL2) não funciona por causa de recursão infinita

### ISSUE THREAD

**Issue by juliafalcao** [wallacebaleroni/Prolog-Top#2]
https://github.com/wallacebaleroni/Prolog-Top/blob/d6da69b23460a4d6e3339f01914028506c1358db/selecao.pl#L278

**Comment by rmparanhos** [comment]
Essa ficaem tem um comportamento estranho, se for true é ok, se for false ele explode

**Comment by wallacebaleroni** [comment]
`pertence(X, Z) :- (ficaem(X, Y), ficaem(Y, Z)) ; ficaem(X, Z).` resolve

**Comment by wallacebaleroni** [comment]
Opa, resolve não

**Comment by juliafalcao** [comment]
resolvemo
